# Generated by Django 4.0.3 on 2022-05-27 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=300)),
                ('video_tumb', models.ImageField(null=True, upload_to='')),
                ('video_title', models.CharField(max_length=150)),
                ('video_tags', models.CharField(max_length=200)),
                ('video_like', models.IntegerField()),
                ('video', models.FileField(null=True, upload_to='')),
                ('vid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
